#! /usr/bin/env bash

set -euo pipefail

# Prepare environment variables
export WORKDIR=$(pwd)

# Always make sure node dependencies are up-to-date
yarn install

# Override node modules as required
modules=$(cd /overrides; ls)

for module in $modules; do
    rm -rf node_modules/$module
    cp -r /overrides/$module node_modules/$module
done

# Run command
$@

